server: 
  port: 8003 
  context-path: /provider 
spring: 
  application: 
    name: microservice-provider    # 项目名称尽量用小写 
  jpa: 
    generate-ddl: false 
    show-sql: true 
    hibernate: 
      ddl-auto: none 
  datasource:                           # 指定数据源 
    platform: h2                        # 指定数据源类型 
    schema: classpath:schemal.sql        # 指定h2数据库的建表脚本 
    data: classpath:data.sql            # 指定h2数据库的insert脚本 
  thymeleaf: 
    cache: false ##close cache 
logging: 
  level: 
    root: INFO 
    org.hibernate: INFO 
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE 
    com.itmuch.youran.persistence: ERROR 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://user:password123@localhost:8761/eureka/    # 指定注册中心的地址 
  instance: 
    preferIpAddress: true 